# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeoulLost' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
  # Pods for SeoulLost
  pod 'Alamofire', '~> 5.2'
  pod 'Kingfisher', '~> 5.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Moya', '~> 14.0'
  
  target 'SeoulLostTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SeoulLostUITests' do
    # Pods for testing
  end

end
